name       : evolution-ews
version    : 3.26.5
release    : 14
source     :
    - https://download.gnome.org/sources/evolution-ews/3.26/evolution-ews-3.26.5.tar.xz : 58ef6fa9a4298c92285eb1eb7f7a395a2158fbcfe23cb7d17a18f984c4823b60
license    : LGPL-2.1
component  : network.mail
summary    : MS Exchange integration through Exchange Web Services
description: |
    MS Exchange integration through Exchange Web Services
builddeps  :
    - pkgconfig(enchant)
    - pkgconfig(evolution-shell-3.0)
    - pkgconfig(libedataserver-1.2)
    - pkgconfig(libical)
    - pkgconfig(libmspack)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libuhttpmock-0.0)
    - pkgconfig(sqlite3)
setup      : |
    %cmake -DLIB_INSTALL_DIR=%libdir% -DSYSCONF_INSTALL_DIR=/etc .
build      : |
    %make
install    : |
    %make_install
