name       : evolution-ews
version    : 3.18.5
release    : 1
source     :
    - https://download.gnome.org/sources/evolution-ews/3.18/evolution-ews-3.18.5.tar.xz : 7e1ed3b18161a620ba358ebf23e4c7aea85c0c5070be3c20a8a2ef012fbcfc55
license    : LGPL-2.1
component  : network.mail
summary    : MS Exchange integration through Exchange Web Services
description: |
    MS Exchange integration through Exchange Web Services
builddeps  :
    - pkgconfig(enchant)
    - pkgconfig(evolution-mail-3.0)
    - pkgconfig(libedataserver-1.2)
    - pkgconfig(libical)
    - pkgconfig(libmspack)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libuhttpmock-0.0)
    - pkgconfig(sqlite3)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
