name       : evolution-ews
version    : 3.28.5
release    : 21
source     :
    - https://download.gnome.org/sources/evolution-ews/3.28/evolution-ews-3.28.5.tar.xz : ccf026e40828300a0097066ae85aaaee900d15315d6af2f8aa6a39d17b827225
license    : LGPL-2.1-only
component  : network.mail
summary    : MS Exchange integration through Exchange Web Services
description: |
    MS Exchange integration through Exchange Web Services
builddeps  :
    - pkgconfig(enchant)
    - pkgconfig(evolution-shell-3.0)
    - pkgconfig(libedataserver-1.2)
    - pkgconfig(libical)
    - pkgconfig(libmspack)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libuhttpmock-0.0)
    - pkgconfig(sqlite3)
setup      : |
    %cmake -DLIB_INSTALL_DIR=%libdir% -DSYSCONF_INSTALL_DIR=/etc .
build      : |
    %make
install    : |
    %make_install
