name       : evolution-ews
version    : 3.26.4
release    : 13
source     :
    - https://download.gnome.org/sources/evolution-ews/3.26/evolution-ews-3.26.4.tar.xz : 0f36c7792d2fb40504903dfe7d912c0b61cf912d0d35fd9900b916153253509a
license    : LGPL-2.1
component  : network.mail
summary    : MS Exchange integration through Exchange Web Services
description: |
    MS Exchange integration through Exchange Web Services
builddeps  :
    - pkgconfig(enchant)
    - pkgconfig(evolution-shell-3.0)
    - pkgconfig(libedataserver-1.2)
    - pkgconfig(libical)
    - pkgconfig(libmspack)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libuhttpmock-0.0)
    - pkgconfig(sqlite3)
setup      : |
    %cmake -DLIB_INSTALL_DIR=%libdir% -DSYSCONF_INSTALL_DIR=/etc .
build      : |
    %make
install    : |
    %make_install
