name       : evolution-ews
version    : 3.34.3
release    : 27
source     :
    - https://download.gnome.org/sources/evolution-ews/3.34/evolution-ews-3.34.3.tar.xz : cfdd2508bec43de653c370c786f97f1c9c43b5cc9a9a4f4d73edc335c954c2c9
license    : LGPL-2.1-only
component  : network.mail
summary    : MS Exchange integration through Exchange Web Services
description: |
    MS Exchange integration through Exchange Web Services
builddeps  :
    - pkgconfig(enchant-2)
    - pkgconfig(evolution-shell-3.0)
    - pkgconfig(libedataserver-1.2)
    - pkgconfig(libical)
    - pkgconfig(libmspack)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libuhttpmock-0.0)
    - pkgconfig(sqlite3)
setup      : |
    %cmake -DLIB_INSTALL_DIR=%libdir% -DSYSCONF_INSTALL_DIR=/etc .
build      : |
    %make
install    : |
    %make_install
