name       : evolution-ews
version    : 3.38.2
release    : 36
source     :
    - https://download.gnome.org/sources/evolution-ews/3.38/evolution-ews-3.38.2.tar.xz : a5767b4c4b9c678bd17fa8d221d60e0433c86a71a0f8196e2957b3ba691f1fa1
license    : LGPL-2.1-only
component  : network.mail
summary    : MS Exchange integration through Exchange Web Services
description: |
    MS Exchange integration through Exchange Web Services
builddeps  :
    - pkgconfig(enchant-2)
    - pkgconfig(evolution-shell-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libedataserver-1.2)
    - pkgconfig(libical)
    - pkgconfig(libmspack)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libuhttpmock-0.0)
    - pkgconfig(sqlite3)
setup      : |
    %cmake -DLIB_INSTALL_DIR=%libdir% -DSYSCONF_INSTALL_DIR=/etc .
build      : |
    %make
install    : |
    %make_install
