name       : evolution-ews
version    : 3.38.3
release    : 37
source     :
    - https://download.gnome.org/sources/evolution-ews/3.38/evolution-ews-3.38.3.tar.xz : 11f67fa989abd9a2bcb380d92c9c0866b0a1de29ac2138af85f5ab48e3be52e8
license    : LGPL-2.1-only
component  : network.mail
summary    : MS Exchange integration through Exchange Web Services
description: |
    MS Exchange integration through Exchange Web Services
builddeps  :
    - pkgconfig(enchant-2)
    - pkgconfig(evolution-shell-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libedataserver-1.2)
    - pkgconfig(libical)
    - pkgconfig(libmspack)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libuhttpmock-0.0)
    - pkgconfig(sqlite3)
setup      : |
    %cmake -DLIB_INSTALL_DIR=%libdir% -DSYSCONF_INSTALL_DIR=/etc .
build      : |
    %make
install    : |
    %make_install
