name       : evolution-ews
version    : 3.40.3
release    : 41
source     :
    - https://download.gnome.org/sources/evolution-ews/3.40/evolution-ews-3.40.3.tar.xz : 640204e6ba4f3b2653dd548f60e475e376cff0d6bb2afd0d411850fa9da8c496
license    : LGPL-2.1-only
component  : network.mail
summary    : MS Exchange integration through Exchange Web Services
description: |
    MS Exchange integration through Exchange Web Services
builddeps  :
    - pkgconfig(enchant-2)
    - pkgconfig(evolution-shell-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libedataserver-1.2)
    - pkgconfig(libical)
    - pkgconfig(libmspack)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libuhttpmock-0.0)
    - pkgconfig(sqlite3)
setup      : |
    %cmake -DLIB_INSTALL_DIR=%libdir% -DSYSCONF_INSTALL_DIR=/etc .
build      : |
    %make
install    : |
    %make_install
